### ISSUE TITLE
How To Use

### ISSUE THREAD

**Issue by danesprockets** [Acumatica/GIToReport#1]
Can you make this so it is an importable customization project or tell us how to use the code in the file using Acumatica directly. I started a new Code File in a customization project and copy pasted your current code and got this error:
```
Building directory '\WebSiteValidationDomain\App_RuntimeCode\'.
\App_RuntimeCode\GIToReport.cs(187): error CS1056: Unexpected character '$'
\App_RuntimeCode\GIToReport.cs(187): error CS1056: Unexpected character '$'
```

A little more instruction in the ReadMe would be nice. Thanks!

**Comment by dropsonic** [comment]
@danesprockets there is a full customization package available on the Releases page.
Here is a direct link to the latest version: https://github.com/Acumatica/GIToReport/files/2125304/GIToReport.zip

Just download it and import on the Customization Projects page, then publish.

**Comment by danesprockets** [comment]
Thanks! I was sent a link to just the GitHub page, not release so did not know there was one.
